# Generated by Django 3.0.2 on 2020-06-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20200603_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
