# Generated by Django 3.0.2 on 2020-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20200604_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
