# Generated by Django 3.0.2 on 2020-06-07 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searches', '0004_auto_20200608_0211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search_Model',
            new_name='SearchModel',
        ),
    ]
